# Generated by Django 2.1.1 on 2018-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_last_change',
            field=models.DateTimeField(null=True),
        ),
    ]
