# Generated by Django 2.1.1 on 2018-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_application_date_last_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_last_change',
        ),
        migrations.AddField(
            model_name='application',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
