version: '2'

services:
  db:
    image: postgres:latest
    container_name: queuerequests_db01
    volumes:
    - ./runtime/postgres_data:/var/lib/postgresql/data:Z
    ports:
    - "5435:5432"
    environment:
    - POSTGRES_PASSWORD=qwerty
    - POSTGRES_DB=queue_db

  redis:
    image: redis
    container_name: queuerequests_redis01
    ports:
    - "6382:6379"
    volumes:
    - ./runtime/redis:/data:Z

  rabbitmq:
    image: rabbitmq
    container_name: queuerequests_rabbitmq01
    ports:
    - "5673:5672"
    volumes:
    - ./runtime/rabbitmq:/data:Z

  web:
    build: .
    container_name: queuerequests_app01
    command: bash -c "python3 /code/manage.py migrate --noinput && python3 /code/manage.py runserver 0.0.0.0:8000"
    depends_on:
    - db
    - redis
    - rabbitmq
    ports:
    - "8080:8000"
    volumes:
    - .:/code
