# Generated by Django 2.1.1 on 2018-09-28 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_app', to='users.Application')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_app', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
