# Generated by Django 2.1.1 on 2018-10-01 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20180928_1159'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_state', models.CharField(max_length=20)),
                ('current_state', models.CharField(max_length=20)),
                ('updated_on', models.DateTimeField(max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_log', to='users.Application')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='change_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
