# Generated by Django 2.1.1 on 2018-09-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('operator', 'Operator')], default='user', max_length=10),
        ),
    ]
